title: Civic Engagement Platform
description: A platform for addressing civic issues across India's 19,101 PIN codes
theme: just-the-docs

url: https://kushalkmrd.github.io/mpga_draft

color_scheme: light

search_enabled: true
enable_copy_code_button: true

footer_content: "Copyright &copy; 2024 Civic Engagement Platform. Distributed under an <a href='https://github.com/kushalkmrd/mpga_draft/blob/main/LICENSE.txt'>MIT license</a>."

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/kushalkmrd/mpga_draft"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

aux_links:
  "GitHub Repository": "https://github.com/kushalkmrd/mpga_draft"

aux_links_new_tab: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus